src/Entity/Album.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=AlbumRepository::class)
 */
class Album
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $spotify_album_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $release_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $total_tracks;

    /**
     * @ORM\ManyToOne(targetEntity=Artist::class, inversedBy="albums")
     * @ORM\JoinColumn(nullable=false)
     */
    private $artist;

    /**
     * @ORM\OneToMany(targetEntity=Favorite::class, mappedBy="album", orphanRemoval=true)
     */
    private $favorite;

    public function __construct()
    {
        $this->favorite = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSpotifyAlbumId(): ?string
    {
        return $this->spotify_album_id;
    }

    public function setSpotifyAlbumId(string $spotify_album_id): self
    {
        $this->spotify_album_id = $spotify_album_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getReleaseDate(): ?string
    {
        return $this->release_date;
    }

    public function setReleaseDate(string $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getTotalTracks(): ?int
    {
        return $this->total_tracks;
    }

    public function setTotalTracks(int $total_tracks): self
    {
        $this->total_tracks = $total_tracks;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    /**
     * @return Collection<int, Favorite>
     */
    public function getFavorite(): Collection
    {
        return $this->favorite;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorite->contains($favorite)) {
            $this->favorite[] = $favorite;
            $favorite->setAlbum($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorite->removeElement($favorite)) {
            // set the owning side to null (unless already changed)
            if ($favorite->getAlbum() === $this) {
                $favorite->setAlbum(null);
            }
        }

        return $this;
    }
}

src/Controller/AdminAlbumController.php
<?php

namespace App\Controller;

use App\Entity\Album;
use App\Form\AlbumType;
use App\Repository\AlbumRepository;
use App\Repository\ArtistRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;

/**
 * @Route("/admin/album")
 */
class AdminAlbumController extends AbstractController
{
    /**
     * @Route("/", name="app_admin_album_index", methods={"GET"})
     */
    public function index(EntityManagerInterface $entityManager, PaginatorInterface $paginator, Request $request): Response
    {
        $dql = 'SELECT a FROM App\Entity\Album a';
        $query = $entityManager->createQuery($dql);

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('admin_album/index.html.twig', [
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route("/new", name="app_admin_album_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AlbumRepository $albumRepository, ArtistRepository $artistRepository): Response
    {
        $album = new Album();
        $artists = $artistRepository->findAll();

        $form = $this->createForm(AlbumType::class, $album, [
            'artists' => $artists
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $albumRepository->add($album, true);

            return $this->redirectToRoute('app_admin_album_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_album/new.html.twig', [
            'album' => $album,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_album_show", methods={"GET"})
     */
    public function show(Album $album): Response
    {
        return $this->render('admin_album/show.html.twig', [
            'album' => $album,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_admin_album_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Album $album, AlbumRepository $albumRepository, ArtistRepository $artistRepository): Response
    {
        $artists = $artistRepository->findAll();

        $form = $this->createForm(AlbumType::class, $album, [
            'artists' => $artists
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $albumRepository->add($album, true);

            return $this->redirectToRoute('app_admin_album_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_album/edit.html.twig', [
            'album' => $album,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_album_delete", methods={"POST"})
     */
    public function delete(Request $request, Album $album, AlbumRepository $albumRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $album->getId(), $request->request->get('_token'))) {
            $albumRepository->remove($album, true);
        }

        return $this->redirectToRoute('app_admin_album_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_album/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_album_delete', {'id': album.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ album.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/admin_album/_form.html.twig
{{ form_start(form) }}
     <div class="mb-3">
        {{ form_row(form.spotify_album_id,{'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.name,{'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.release_date,{'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.total_tracks,{'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.artist,{'attr': {'class': 'form-control'}}) }}
    </div>
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_album/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Album{% endblock %}

{% block body %}
    <h1>Edit Album</h1>

    {{ include('admin_album/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_album_index') }}">back to list</a>

    {{ include('admin_album/_delete_form.html.twig') }}
{% endblock %}

templates/admin_album/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album index{% endblock %}

{% block body %}
    <h1>Album index</h1>
    <a href="{{ path('app_admin_album_new') }}" class="btn btn-primary">Create new</a>
    <table class="table">
        <thead>
            <tr>
                <th>{{ knp_pagination_sortable(pagination, 'Id', 'a.id') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Name', 'a.name') }}</th>
                <th>Release_date</th>
                <th>{{ knp_pagination_sortable(pagination, 'Total tracks', 'a.total_tracks') }}</th>
                <th>Artist</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for album in pagination %}
            <tr>
                <td>{{ album.id }}</td>
                <td>{{ album.name }}</td>
                <td>{{ album.releaseDate }}</td>
                <td>{{ album.totalTracks }}</td>
                <td>{{ album.artist.name }}</td>
                <td>
                    <a href="{{ path('app_admin_album_show', {'id': album.id}) }}" class="btn btn-success">show</a>
                    <a href="{{ path('app_admin_album_edit', {'id': album.id}) }}" class="btn btn-primary">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}

templates/admin_album/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Album{% endblock %}

{% block body %}
    <h1>Create new Album</h1>

    {{ include('admin_album/_form.html.twig') }}

    <a href="{{ path('app_admin_album_index') }}">back to list</a>
{% endblock %}

templates/admin_album/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album{% endblock %}

{% block body %}
    <h1>Album</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ album.id }}</td>
            </tr>
            <tr>
                <th>Spotify_album_id</th>
                <td>{{ album.spotifyAlbumId }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ album.name }}</td>
            </tr>
            <tr>
                <th>Release_date</th>
                <td>{{ album.releaseDate }}</td>
            </tr>
            <tr>
                <th>Total_tracks</th>
                <td>{{ album.totalTracks }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_album_index') }}">back to list</a>

    <a href="{{ path('app_admin_album_edit', {'id': album.id}) }}" class="btn btn-primary">edit</a>

    {{ include('admin_album/_delete_form.html.twig') }}
{% endblock %}