src/Entity/Album.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=AlbumRepository::class)
 */
class Album
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $spotify_album_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $release_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $total_tracks;

    /**
     * @ORM\ManyToOne(targetEntity=Artist::class, inversedBy="albums")
     * @ORM\JoinColumn(nullable=false)
     */
    private $artist;

    /**
     * @ORM\OneToMany(targetEntity=Favorite::class, mappedBy="album", orphanRemoval=true)
     */
    private $favorite;

    public function __construct()
    {
        $this->favorite = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSpotifyAlbumId(): ?string
    {
        return $this->spotify_album_id;
    }

    public function setSpotifyAlbumId(string $spotify_album_id): self
    {
        $this->spotify_album_id = $spotify_album_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getReleaseDate(): ?string
    {
        return $this->release_date;
    }

    public function setReleaseDate(string $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getTotalTracks(): ?int
    {
        return $this->total_tracks;
    }

    public function setTotalTracks(int $total_tracks): self
    {
        $this->total_tracks = $total_tracks;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    /**
     * @return Collection<int, Favorite>
     */
    public function getFavorite(): Collection
    {
        return $this->favorite;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorite->contains($favorite)) {
            $this->favorite[] = $favorite;
            $favorite->setAlbum($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorite->removeElement($favorite)) {
            // set the owning side to null (unless already changed)
            if ($favorite->getAlbum() === $this) {
                $favorite->setAlbum(null);
            }
        }

        return $this;
    }
}

src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArtistRepository::class)
 */
class Artist
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $followers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $spotify_artist_id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $image_link;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $popularity;

    /**
     * @ORM\Column(type="text")
     */
    private $genre;

    /**
     * @ORM\OneToMany(targetEntity=Album::class, mappedBy="artist", orphanRemoval=true)
     */
    private $albums;

    public function __construct()
    {
        $this->albums = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFollowers(): ?int
    {
        return $this->followers;
    }

    public function setFollowers(int $followers): self
    {
        $this->followers = $followers;

        return $this;
    }

    public function getSpotifyArtistId(): ?string
    {
        return $this->spotify_artist_id;
    }

    public function setSpotifyArtistId(string $spotify_artist_id): self
    {
        $this->spotify_artist_id = $spotify_artist_id;

        return $this;
    }

    public function getImageLink(): ?string
    {
        return $this->image_link;
    }

    public function setImageLink(?string $image_link): self
    {
        $this->image_link = $image_link;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPopularity(): ?int
    {
        return $this->popularity;
    }

    public function setPopularity(int $popularity): self
    {
        $this->popularity = $popularity;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    /**
     * @return Collection<int, Album>
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }

    public function addAlbum(Album $album): self
    {
        if (!$this->albums->contains($album)) {
            $this->albums[] = $album;
            $album->setArtist($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): self
    {
        if ($this->albums->removeElement($album)) {
            // set the owning side to null (unless already changed)
            if ($album->getArtist() === $this) {
                $album->setArtist(null);
            }
        }

        return $this;
    }
}

src/Form/ArtistType.php
<?php

namespace App\Form;

use App\Entity\Artist;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Validator\Constraints\Positive;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;

class ArtistType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('followers', IntegerType::class, [
                'constraints' => [
                    new Positive([
                        'message' => 'The number of followers must be positive'
                    ])
                ]
            ])
            ->add('spotify_artist_id', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Spotify artist id could not be empty',
                    ])
                ]
            ])
            ->add('image_link')
            ->add('name', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Name could not be empty'
                    ]),
                    new Length([
                        'min' => 2,
                        'max' => 255,
                        'minMessage' => 'The name could not be shorter than 2 characters',
                        'maxMessage' => 'The name could not be longer than 255 characters'
                    ])
                ]
            ])
            ->add('popularity', IntegerType::class, [
                'constraints' => [
                    new Positive([
                        'message' => 'The number of popularity must be positive'
                    ])
                ]
            ])
            ->add('genre', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'Genre could be empty'
                    ])
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Artist::class,
        ]);
    }
}

src/Controller/ArtistController.php
<?php

namespace App\Controller;

use App\Entity\Artist;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;

class ArtistController extends AbstractController
{
    /**
     * @Route("/user/artist", name="app_artist")
     */
    public function index(EntityManagerInterface $entityManager, PaginatorInterface $paginator, Request $request): Response
    {
        $dql = 'SELECT a FROM App\Entity\Artist a';
        $query = $entityManager->createQuery($dql);

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('artist/index.html.twig', [
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route("/user/artist/{id}", name="app_artist_show", methods={"GET"})
     */
    public function show(Artist $artist): Response
    {
        return $this->render('artist/show.html.twig', [
            'artist' => $artist,
        ]);
    }
}

templates/artist/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist index{% endblock %}

{% block body %}
    <h1>Artist index</h1>
    <table class="table">
        <thead>
            <tr>
                <th>{{ knp_pagination_sortable(pagination, 'Id', 'a.id') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Followers', 'a.followers') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Name', 'a.name') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Popularity', 'a.popularity') }}</th>
                <th>Album</th>
                <th>Genre</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for artist in pagination %}
            <tr>
                <td>{{ artist.id }}</td>
                <td>{{ artist.followers }}</td>
                <td>{{ artist.name }}</td>
                <td>{{ artist.popularity }}</td>
                <td><a href="{{ path('app_artist_show', {'id': artist.id}) }}">Albums</a></td>
                <td>{{ artist.genre }}</td>
                <td>
                    <a href="{{ path('app_artist_show', {'id': artist.id}) }}" class="btn btn-success">show</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<div class="navigation">
    {{ knp_pagination_render(pagination) }}
</div>
{% endblock %}

templates/artist/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist index{% endblock %}

{% block body %}
    <section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{{ path('app_dashboard') }}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ path('app_artist') }}">Artists</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{artist.name}}</li>
          </ol>
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="{{artist.imageLink}}" alt="avatar"
              class="rounded-circle img-fluid" style="width: 150px;">
            <h5 class="my-3">{{artist.name}}</h5>
            <p class="text-muted mb-1">Popularity : {{artist.popularity}}</p>
            <p class="text-muted mb-4">Followers : {{artist.followers}}</p>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
                <div class="row">
                    <div class="col-sm-3">
                        <p class="mb-0">Album Name</p>
                    </div>
                    <div class="col-sm-3">
                        <p class="mb-0">Release date</p>
                    </div>
                    <div class="col-sm-3">
                        <p class="mb-0">Total tracks</p>
                    </div>
                    <div class="col-sm-3">
                        <p class="mb-0">Favorite</p>
                    </div>
                </div>
                <hr>
            {% for album in artist.albums %}
                <div class="row">
                    <div class="col-sm-3">
                        <p class="mb-0">{{album.name}}</p>
                    </div>
                    <div class="col-sm-3">
                        <p class="mb-0">{{album.releaseDate}}</p>
                    </div>
                    <div class="col-sm-3">
                        <p class="mb-0">{{album.totalTracks}}</p>
                    </div>
                    <div class="col-sm-3">
                        <a href="{{ path('app_favorite_album', {'id': album.id}) }}" class="btn btn-primary">Favorite</a>
                    </div>
                </div>
                <hr>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}


            