src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArtistRepository::class)
 */
class Artist
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $followers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $spotify_artist_id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $image_link;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $popularity;

    /**
     * @ORM\Column(type="text")
     */
    private $genre;

    /**
     * @ORM\OneToMany(targetEntity=Album::class, mappedBy="artist", orphanRemoval=true)
     */
    private $albums;

    public function __construct()
    {
        $this->albums = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFollowers(): ?int
    {
        return $this->followers;
    }

    public function setFollowers(int $followers): self
    {
        $this->followers = $followers;

        return $this;
    }

    public function getSpotifyArtistId(): ?string
    {
        return $this->spotify_artist_id;
    }

    public function setSpotifyArtistId(string $spotify_artist_id): self
    {
        $this->spotify_artist_id = $spotify_artist_id;

        return $this;
    }

    public function getImageLink(): ?string
    {
        return $this->image_link;
    }

    public function setImageLink(?string $image_link): self
    {
        $this->image_link = $image_link;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPopularity(): ?int
    {
        return $this->popularity;
    }

    public function setPopularity(int $popularity): self
    {
        $this->popularity = $popularity;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    /**
     * @return Collection<int, Album>
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }

    public function addAlbum(Album $album): self
    {
        if (!$this->albums->contains($album)) {
            $this->albums[] = $album;
            $album->setArtist($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): self
    {
        if ($this->albums->removeElement($album)) {
            // set the owning side to null (unless already changed)
            if ($album->getArtist() === $this) {
                $album->setArtist(null);
            }
        }

        return $this;
    }
}

src/Controller/AdminArtistController.php
<?php

namespace App\Controller;

use App\Entity\Artist;
use App\Form\ArtistType;
use App\Repository\ArtistRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;

/**
 * @Route("/admin/artist")
 */
class AdminArtistController extends AbstractController
{
    /**
     * @Route("/", name="app_admin_artist_index", methods={"GET"})
     */
    public function index(EntityManagerInterface $entityManager, PaginatorInterface $paginator, Request $request): Response
    {
        $dql = 'SELECT a FROM App\Entity\Artist a';
        $query = $entityManager->createQuery($dql);

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        return $this->render('admin_artist/index.html.twig', [
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route("/new", name="app_admin_artist_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ArtistRepository $artistRepository): Response
    {
        $artist = new Artist();

        $form = $this->createForm(ArtistType::class, $artist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artistRepository->add($artist, true);

            return $this->redirectToRoute('app_admin_artist_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_artist/new.html.twig', [
            'artist' => $artist,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_artist_show", methods={"GET"})
     */
    public function show(Artist $artist): Response
    {
        return $this->render('admin_artist/show.html.twig', [
            'artist' => $artist,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_admin_artist_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Artist $artist, ArtistRepository $artistRepository): Response
    {
        $form = $this->createForm(ArtistType::class, $artist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artistRepository->add($artist, true);

            return $this->redirectToRoute('app_admin_artist_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_artist/edit.html.twig', [
            'artist' => $artist,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_artist_delete", methods={"POST"})
     */
    public function delete(Request $request, Artist $artist, ArtistRepository $artistRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $artist->getId(), $request->request->get('_token'))) {
            $artistRepository->remove($artist, true);
        }

        return $this->redirectToRoute('app_admin_artist_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_artist/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_artist_delete', {'id': artist.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artist.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/admin_artist/_form.html.twig
{{ form_start(form) }}
    <div class="mb-3">
        {{ form_row(form.followers,{'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.spotify_artist_id,{'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.image_link,{'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.name,{'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.popularity,{'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.genre,{'attr': {'class': 'form-control'}}) }}
    </div>
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_artist/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Artist{% endblock %}

{% block body %}
    <h1>Edit Artist</h1>

    {{ include('admin_artist/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_artist_index') }}">back to list</a>

    {{ include('admin_artist/_delete_form.html.twig') }}
{% endblock %}

templates/admin_artist/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist index{% endblock %}

{% block body %}
    <h1>Artist index</h1>
    <a href="{{ path('app_admin_artist_new') }}" class="btn btn-primary">Create new</a>

    <table class="table">
        <thead>
            <tr>
                <th>{{ knp_pagination_sortable(pagination, 'Id', 'a.id') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Followers', 'a.followers') }}</th>
                <th>Spotify_artist_id</th>
                <th>Image_link</th>
                <th>{{ knp_pagination_sortable(pagination, 'Name', 'a.name') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'Popularity', 'a.popularity') }}</th>
                <th>Genre</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for artist in pagination %}
            <tr>
                <td>{{ artist.id }}</td>
                <td>{{ artist.followers }}</td>
                <td>{{ artist.spotifyArtistId }}</td>
                <td>{{ artist.imageLink }}</td>
                <td>{{ artist.name }}</td>
                <td>{{ artist.popularity }}</td>
                <td>{{ artist.genre }}</td>
                <td>
                    <a href="{{ path('app_admin_artist_show', {'id': artist.id}) }}" class="btn btn-success">show</a>
                    <a href="{{ path('app_admin_artist_edit', {'id': artist.id}) }}" class="btn btn-primary">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<div class="navigation">
    {{ knp_pagination_render(pagination) }}
</div>
{% endblock %}

templates/admin_artist/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Artist{% endblock %}

{% block body %}
    <h1>Create new Artist</h1>

    {{ include('admin_artist/_form.html.twig') }}

    <a href="{{ path('app_admin_artist_index') }}">back to list</a>
{% endblock %}

templates/admin_artist/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist{% endblock %}

{% block body %}
    <h1>Artist</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ artist.id }}</td>
            </tr>
            <tr>
                <th>Followers</th>
                <td>{{ artist.followers }}</td>
            </tr>
            <tr>
                <th>Spotify_artist_id</th>
                <td>{{ artist.spotifyArtistId }}</td>
            </tr>
            <tr>
                <th>Image_link</th>
                <td>{{ artist.imageLink }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ artist.name }}</td>
            </tr>
            <tr>
                <th>Popularity</th>
                <td>{{ artist.popularity }}</td>
            </tr>
            <tr>
                <th>Genre</th>
                <td>{{ artist.genre }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_artist_index') }}">back to list</a>

    <a href="{{ path('app_admin_artist_edit', {'id': artist.id}) }}" class="btn btn-warning">edit</a>

    {{ include('admin_artist/_delete_form.html.twig') }}
{% endblock %}